//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace User
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Firm
	{
		public virtual int IdFirm
		{
			get;
			set;
		}

		public virtual string Name
		{
			get;
			set;
		}
	}
}

