//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace User
{
    //using Expertise;
    //using Interview;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class User
	{
		public virtual int IdUser
		{
			get;
			set;
		}

		public virtual string FirstName
		{
			get;
			set;
		}

		public virtual string LastName
		{
			get;
			set;
		}

		public virtual bool IsActive
		{
			get;
			set;
		}

        [ForeignKey("NumFirm")]
		public virtual int NumFirm
		{
			get;
			set;
		}

		public virtual int NumUserRole
		{
			get;
			set;
		}

	}
}

